### PR TITLE
feat: add rpms-signature-scan task to .tekton pipelines

### PR DESCRIPTION
**Pull request by johnbieren**

### CODE REVIEW

**Review by happybhati — APPROVED** [review]

**Comment by mmalina** [comment]
Here's a PR to copy cosign from the RHTAS cosign image instead of installing an unsigned rpm from the upstream cosign project on github: https://github.com/konflux-ci/release-service-utils/pull/271

When merged, that should get rid of the EC violation.

**Review by davidmogar — APPROVED** [review]

**Pull request merged**
