### PR TITLE
fix(marketplacesvm): path regex

### PR DESCRIPTION
**Pull request by JAVGan**
This commit updates the regex patter for validating the staged directory path string.

### CODE REVIEW

**Review by johnbieren — APPROVED** [review]

**Comment by JAVGan** [comment]
Any sggestions for gitlint? I'm still not very used to that

**Comment by johnbieren** [comment]
I think it is the Update vs update in commit title

**Comment by johnbieren** [comment]
nvm your commit title isn't the pr title. I think it is the missing `:` then

**Comment by johnbieren** [comment]
You want this merged once it passes CI right?

**Comment by JAVGan** [comment]
> You want this merged once it passes CI right?

Yes, please!

Then once the new image is built I need to change the tag on https://github.com/konflux-ci/release-service-catalog/pull/719

**Comment by johnbieren** [comment]
I don't know why `ok-to-test` seemingly doesn't grant approval in this repo. We don't have e2e here anyways though. Merging

**Pull request merged**
