### PR TITLE
fix(deps): adds packaging module on Dockerfile

### PR DESCRIPTION
**Pull request by JAVGan**
Add missing dependency `packaging` for `pubtools-marketplacesvm`

### CODE REVIEW

**Comment by JAVGan** [comment]
@mmalina PTAL

**Review by johnbieren — APPROVED** [review]

**Comment by johnbieren** [comment]
All of our build pipelines are broken (I have a support thread open for it) which fails the check here

**Comment by johnbieren** [comment]
Build pipeline fixed, can you rebase?

**Pull request merged**
